services:
  http:
    build: &default-build-spec
      context: .
      dockerfile: Dockerfile
      target: http
    network_mode: "host"

  irc:
    build:
      <<: *default-build-spec
      target: irc
    volumes: &default-logs-bind
      - type: bind
        source: ${DRC_LOGS_PATH_HOST:?"Must define DRC_LOGS_PATH_HOST as the absolute path to logs on the host."}
        target: /logs
    network_mode: "host"

  discord:
    build:
      <<: *default-build-spec
      target: discord
    volumes: *default-logs-bind
    network_mode: "host"
    restart: "on-failure"

volumes:
  logs:
    external: true
